security:
    password_hashers:
        App\Entity\User:
            algorithm: sodium

        App\Entity\Client:
            algorithm: sodium

    providers:
        db_provider:
            entity:
                class: App\Entity\User
                property: username

        client_provider:
            entity:
                class: App\Entity\Client
                property: username

    firewalls:
        login:
            pattern: ^/login
            user_checker: App\Security\UserChecker
            stateless: true
            provider: db_provider

            login_throttling:
                max_attempts: 5
                interval: '1 minute'

            json_login:
                check_path: /login
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure

        client_login:
            pattern: ^/frontend/login
            user_checker: App\Security\ClientChecker
            stateless: true
            provider: client_provider

            login_throttling:
                max_attempts: 5
                interval: '1 minute'

            json_login:
                check_path: /frontend/login
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure

        frontend_profile:
            pattern: ^/frontend/profile
            provider: client_provider
            user_checker: App\Security\ClientChecker
            stateless: true
            jwt: ~

        docs:
            pattern: ^/docs
            provider: db_provider
            user_checker: App\Security\UserChecker
            stateless: true
            http_basic: ~

        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        api:
            pattern: ^/
            provider: db_provider
            user_checker: App\Security\UserChecker
            stateless: true
            jwt: ~

    access_control:
        - { path: ^/login$, roles: PUBLIC_ACCESS }
        - { path: ^/frontend/login$, roles: PUBLIC_ACCESS }

        - { path: ^/frontend/profile, roles: ROLE_CLIENT }

        - { path: ^/docs, roles: ROLE_USER }

        - { path: ^/frontend, roles: ROLE_CLIENT }

        - { path: ^/, roles: ROLE_USER }

when@test:
    security:
        password_hashers:
            App\Entity\User:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10

            App\Entity\Client:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10
