FROM inshopgroup/docker-inshop-crm-api-php-fpm-prod:php8.1

WORKDIR /var/www

COPY --chown=www-data:www-data composer.json composer.lock symfony.lock ./

RUN composer install \
    --no-dev \
    --no-interaction \
    --no-progress \
    --prefer-dist \
    --optimize-autoloader \
    --no-scripts

COPY --chown=www-data:www-data bin/ ./bin/
COPY --chown=www-data:www-data config/ ./config/
COPY --chown=www-data:www-data migrations/ ./migrations/
COPY --chown=www-data:www-data public/ ./public/
COPY --chown=www-data:www-data src/ ./src/
COPY --chown=www-data:www-data translations/ ./translations/

RUN mkdir -p var/cache var/log \
    && chown -R www-data:www-data var

USER www-data

RUN composer dump-autoload \
    --no-dev \
    --classmap-authoritative \
    --no-interaction
